# Helper functions test

In [1]:
import helper_functions

In [2]:
#Authenticate function
#helper_functions.authenticate()

In [3]:
#Get available reports function
#helper_functions.get_available_reports()

In [4]:
#Get report key function
report_file_path = "/content/folder[@name='zzzCompany Folders']/folder[@name='Proliance Surgeons, Inc., P.S.']/folder[@name='UltiPro']/folder[@name='Export to SQL']/report[@name='Pre-Check Master']"
report_key = helper_functions.get_report_key(report_file_path)

In [5]:
#Get report function
helper_functions.retrieve_report(report_key)

,period_control_date,period_control,period_end_date,employee_number,"last,_first_mi",location_code,org_level_1_code,org_level_2_code,hourly_pay_rate,annual_salary,job_code,job_title,total_hours,check_amount,direct_deposit_amount,net_amount,total_earning_amount,total_deduction_amount,total_taxes
0,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,000000255,"Harmon, Kurt E.",007700,007700,001,17.341101,36069.49,300,Physician,0,0,0,0,0,0,0
1,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,000000290,"Kim, Helen H.",006000,006000,001,17.341101,36069.49,300,Physician,0,0,0,0,0,0,0
2,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,000010074,"Shapiro, Joel A.",000200,000200,001,17.341101,36069.49,300,Physician,0,0,0,0,0,0,0
3,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,000060084,"Barker, Howard B.",000600,000600,001,17.341101,36069.49,300,Physician,0,0,0,0,0,0,0
4,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,000060115,"Havener, Todd W.",000600,000600,001,17.341101,36069.49,300,Physician,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,001008395,"Clinkscales, William B.",004600,004600,001,40.384615,84000,301,Physician Emp,80,0,2813.22,2813.22,3230.77,0,417.55
228,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,001008465,"Gorbaty, Jacob D.",001500,001500,001,156.25,325000,300,Physician,80,0,8297.66,8297.66,12500,0,4202.34
229,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,001008494,"Barrett, Kody K.",002500,002500,001,17.341101,36069.49,303,Physician NS,0,0,0,0,0,0,0
230,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,001008499,"Oh, Daniel C.",002800,002800,001,17.341101,36069.49,301,Physician Emp,0,0,0,0,0,0,0
231,2022-11-25T00:00:00,202211251,2022-11-19T00:00:00,001008518,"Gupta, Neel A.",001900,001900,001,156.25,325000,300,Physician,80,0,8297.67,8297.67,12500,0,4202.33